### ISSUE TITLE
Empty variable RAND_SRC

### ISSUE THREAD

**Issue by HnxArthur** [libecc/libecc#5]
https://github.com/libecc/libecc/blob/d603d5274cd494bac166288e43a62be6d0e70f98/Makefile#L85

RAND_SRC isn't assigned, is it normal ? Should it be EXT_DEPS_SRC instead, to get rand.c file ?

**Comment by rben-dev** [comment]
Hi,

You are perfectly right, this `$(RAND_SRC)` is a reminiscence of old source tree. This should be removed in commit 7590e99.

Thanks,

**Comment by rben-dev** [comment]
@HnxArthur : closing the issue, do not hesitate to reopen it or open a new one if something is still pending.
