### ISSUE TITLE
[SOLVED] ERROR: undefined reference to "nn_consistency_check"

### ISSUE THREAD

**Issue by dngtuankiet** [libecc/libecc#7]
Hello everyone,
I am trying to cross-compile libecc on RISC-V platforms.
However I encountered the "nn_consistency_check" error, even though I had added the flag -DWORDSIZE=32 when compiling the static libraries and my software test.

Here is my configuration for the static library build:
`export LIBECC_NOSTDLIB=1
make clean
CROSS_COMPILE=riscv64-unknown-elf- CC=gcc CFLAGS="-march=rv32imac -mabi=ilp32 -W -Wextra -Wall -Wunreachable-code \
-pedantic -fno-builtin -std=c99 -Os \
-ffreestanding -fno-builtin -nostdlib \
--specs=htif_nano.specs -DCUSTOM_RAND_GENERATE -DWORDSIZE=32 -DUSER_NN_BIT_LEN=256" \
LDFLAGS="-T htif.ld" \
make build/libarith.a build/libec.a
`
Here is the result from my terminal:
![image](https://github.com/libecc/libecc/assets/54100170/52411ed2-106c-4825-9200-415baa0b6dce)

**Comment by rben-dev** [comment]
Hi,

It is not easy to reproduce your compilation toolchain without further information: can you please provide a complete scenario of compilation, ideally with your makefiles, and with e.g. your `htif_nano.specs`.

Anyways, I have spotted a potential issue that might not help proper compilation: there is a mismatch in the `march` flags between the library and the binary: the former uses `rv32imac` while the latter uses `rv32i` (which is a strict subset).

Also, the **maximum digest size** of the library also influences the consistency check: if the configured hashes are not the same between the compiled static library and the folder where you compile the utility binaries, the error will be triggered.

Regards,

**Comment by dngtuankiet** [comment]
Thank you for your reply.

1. Here is the link to my repo, and you can see the content of my `Makefile-libecc`: [https://github.com/dngtuankiet/RISCVConsoleCode/blob/dev/Makefile-libecc](url)
Also, the `htif_nano.specs` is in this repo of UC-Berkeley: [https://github.com/ucb-bar/libgloss-htif/blob/master/util/htif_nano.specs](url)

2. Regarding the mismatch of `rv32imac` and `rv32i`, I have fixed this to `rv32imac` as this is also the configuration of my hardware.

3. If you means configuring the curves, hash, sign and schemes in the `lib_ecc_config.h`, I wanted to select one algorithm for each and tried to override the configuration (as in the `Makefile-libecc`).

Also here is my current bash-script to build the library:
```
#--------------------------RISC-V build-----------------------#
export LIBECC_NOSTDLIB=1
make clean

CROSS_COMPILE=riscv64-unknown-elf- CC=gcc CFLAGS="-march=rv32imac -mabi=ilp32 -W -Wextra -Wall -Wunreachable-code \
-pedantic -fno-builtin -std=c99 -Os \
-ffreestanding -fno-builtin -nostdlib \
--specs=htif_nano.specs -DCUSTOM_RAND_GENERATE -DWORDSIZE=32 -DUSER_NN_BIT_LEN=256 -DWITH_LIBECC_CONFIG_OVERRIDE -DWITH_CURVE_SECP256K1 -DWITH_HASH_SHA256 -DWITH_SIG_ECDSA -DWITH_ECCCDH" \
LDFLAGS="-T htif.ld" \
make build/libarith.a build/libec.a build/ligsign.a
#-------------------------------------------------------------#
```
=========================================================
After recheck the Makefile line by line, I have found the problem. It's because I did not add the library at linking step.
For now, all is good. 

I appreciate your help @rben-dev. Thank you!

**Comment by rben-dev** [comment]
Great if you found the issue, and no problem for the help :-)

Closing the issue as it is resolved!
